title: Emre Ekinci
email: 
description: Emre Ekinci's website
url: "https://ekinci.xyz"
twitter: ekincixyz

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
